const KEYWORDS = [
  "election",
  "elect",
  "president",
  "presidential",
  "congress",
  "congressional",
  "senate",
  "senator",
  "house of representatives",
  "representative",
  "vote",
  "voter",
  "ballot",
  "referendum",
  "democrat",
  "democratic",
  "republican",
  "gop",
  "trump",
  "biden",
  "harris",
  "obama",
  "governor",
  "midterm",
  "primary",
  "inaugural",
  "legislation",
  "supreme court",
  "white house",
  "cabinet",
  "impeach",
  "filibuster",
  "majority leader",
  "speaker of the house",
  "executive order",
  "nato",
  "g7",
  "g20",
  "tariff",
  "sanction",
  "prime minister",
  "parliament",
  "chancellor",
  "zelensky",
  "putin",
  "xi jinping",
  "macron",
  "political party",
];

export function isPoliticsMarket(title: string): boolean {
  const lower = title.toLowerCase();
  return KEYWORDS.some((kw) => lower.includes(kw));
}
